### ISSUE TITLE
num & denom = 0 in _compute_expected_direction

### ISSUE THREAD

**Issue by diegoantognini** [Ardavans/sHDP#7]
Hi,

First, thank you for this project ! I really liked the paper and have directly downloaded the github. 

I tried the example with nips, works fine. However, I wanted to use it on another dataset and other word embeddings. I used the exact same file format.

However, I got an error in the method _compute_expected_direction:
Traceback (most recent call last):
  File "./runner.py", line 225, in <module>
    HDPRunner(args)
  File "./runner.py", line 121, in HDPRunner
    components=[vonMisesFisherLogNormal(**obs_hypparams) for itr in range(K)]
  File "./runner.py", line 121, in <listcomp>
    components=[vonMisesFisherLogNormal(**obs_hypparams) for itr in range(K)]
  File "/root/sHDP/core/core_distributions.py", line 244, in __init__
    self.resample() # initialize from prior
  File "/root/sHDP/core/core_distributions.py", line 425, in resample
    self._Expected_mu = self._compute_expected_direction( D, self.mu_0, self.C_0 )
  File "/root/sHDP/core/core_distributions.py", line 303, in _compute_expected_direction
    val = num/denom*direct
FloatingPointError: invalid value encountered in double_scalars

As observation, in this case, num & denom = 0.0. With the nips case (without any changed in the repo), at the beginning these have some values and quickly "inf". I don't know if this behavior is expected.

So 2 questions:
- How can I fix to avoid null denom ?
- Are the values "inf" for num & denom expected at some points ?

Thank you very much for your help !

EDIT: using your word embeddings work. However, using these I've trained and with a dimension of 500 (also changed in runner.py), it doesn't. I did the L2 normalization for each embedding, the input text contains words with existing word embeddings. What could I make wrong ?

**Comment by Ardavans** [comment]
Hi Diego,

Thank you for your interest in sHDP! The issue that you have now is
typically caused by a problem with your dataset. For instance, one common
problem is having empty documents. Another one could be having unnormalized
word vectors. Please double check your dataset for these problems and let
me know if the problem persists.

Regarding your second question, that behavior is normal (although not
ideal).

**Comment by diegoantognini** [comment]
Thank you for your answer.

As I said in the edit, using your word embeddings works, thus it's not a problem with the dataset. However I've checked the dataset and none of the documents are empty.

For the word vectors, all of them are L2 normalized and non-zero.

Anyway, I'll dig. Thank you !

**Comment by diegoantognini** [comment]
Still trying to find the reason, but I really don't find any clues. Do you have some others ?

**Comment by Ardavans** [comment]
One thing that you can try is changing the hyperparameters. Can you try
changing the hyperparameters
<https://github.com/Ardavans/sHDP/blob/master/runner.py#L120> for the vmf
distribution? Also maybe changing the minibatch size can help. Let me know
if the problem remains for any hyperparameter setting that you try.

**Comment by diegoantognini** [comment]
Thank you for your answer. I've trained other word embeddings, it seems to work fine with the same preprocessing, so cross the finger the training ends without any problem :)

**Comment by Ardavans** [comment]
Awesome! Let me know if you have any other issues.
